/*
 * MicrovisionChain API Document
 *
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.11
 * Contact: heqiming@metasv.com
 * Generated by: https://openapi-generator.tech
 */

/// AddressUtxo : Utxos by address(or addresses) order by height asc.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddressUtxo {
    /// paging flag
    #[serde(rename = "flag", skip_serializing_if = "Option::is_none")]
    pub flag: Option<String>,
    /// Address of the utxo
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// txid of the utxo
    #[serde(rename = "txid", skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
    /// output index in the tx
    #[serde(rename = "outIndex", skip_serializing_if = "Option::is_none")]
    pub out_index: Option<i32>,
    /// Value of the utxo
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<i64>,
    /// Height of the utxo, -1 if not confirmed
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i64>,
}

impl AddressUtxo {
    /// Utxos by address(or addresses) order by height asc.
    pub fn new() -> AddressUtxo {
        AddressUtxo {
            flag: None,
            address: None,
            txid: None,
            out_index: None,
            value: None,
            height: None,
        }
    }
}


