/*
 * MicrovisionChain API Document
 *
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.11
 * Contact: heqiming@metasv.com
 * Generated by: https://openapi-generator.tech
 */

/// ClientPubkeyRequest : Request object to register(or delete) a new client public key.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ClientPubkeyRequest {
    /// The hex format public key to register. (i.e. 02fd17dd0c52e54e5eed4ebe1e75df5e48df422f81c26520d44380bef1691fdd98)
    #[serde(rename = "pubkey", skip_serializing_if = "Option::is_none")]
    pub pubkey: Option<String>,
}

impl ClientPubkeyRequest {
    /// Request object to register(or delete) a new client public key.
    pub fn new() -> ClientPubkeyRequest {
        ClientPubkeyRequest {
            pubkey: None,
        }
    }
}


