/*
 * MicrovisionChain API Document
 *
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.11
 * Contact: heqiming@metasv.com
 * Generated by: https://openapi-generator.tech
 */

/// ContractNftAuctionUtxo : Contract nft auction Utxo belongs to the specified address



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContractNftAuctionUtxo {
    /// Address string of this utxo
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Txid for this utxo.
    #[serde(rename = "txid", skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
    /// Output index for the Utxo.
    #[serde(rename = "txIndex", skip_serializing_if = "Option::is_none")]
    pub tx_index: Option<i32>,
    /// bidMvcPrice
    #[serde(rename = "bidMvcPrice", skip_serializing_if = "Option::is_none")]
    pub bid_mvc_price: Option<i64>,
    /// bidTimestamp
    #[serde(rename = "bidTimestamp", skip_serializing_if = "Option::is_none")]
    pub bid_timestamp: Option<i64>,
    /// bidderAddressPkh
    #[serde(rename = "bidderAddressPkh", skip_serializing_if = "Option::is_none")]
    pub bidder_address_pkh: Option<String>,
    /// Codehash of this utxo.
    #[serde(rename = "codeHash", skip_serializing_if = "Option::is_none")]
    pub code_hash: Option<String>,
    /// Genesis of this utxo.
    #[serde(rename = "genesis", skip_serializing_if = "Option::is_none")]
    pub genesis: Option<String>,
    /// endTimestamp
    #[serde(rename = "endTimestamp", skip_serializing_if = "Option::is_none")]
    pub end_timestamp: Option<i64>,
    /// feeAddressPkh
    #[serde(rename = "feeAddressPkh", skip_serializing_if = "Option::is_none")]
    pub fee_address_pkh: Option<String>,
    /// feeAmount
    #[serde(rename = "feeAmount", skip_serializing_if = "Option::is_none")]
    pub fee_amount: Option<i64>,
    /// feeRate
    #[serde(rename = "feeRate", skip_serializing_if = "Option::is_none")]
    pub fee_rate: Option<i32>,
    /// The height of this utxo, -1 for unconfirmed utxo.
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i64>,
    /// nftCodeHash
    #[serde(rename = "nftCodeHash", skip_serializing_if = "Option::is_none")]
    pub nft_code_hash: Option<String>,
    /// nftId of the auctioning fnt
    #[serde(rename = "nftId", skip_serializing_if = "Option::is_none")]
    pub nft_id: Option<String>,
    /// senderAddressPkh
    #[serde(rename = "senderAddressPkh", skip_serializing_if = "Option::is_none")]
    pub sender_address_pkh: Option<String>,
    /// SensibleId of the utxo
    #[serde(rename = "sensibleId", skip_serializing_if = "Option::is_none")]
    pub sensible_id: Option<String>,
    /// startMvcPrice
    #[serde(rename = "startMvcPrice", skip_serializing_if = "Option::is_none")]
    pub start_mvc_price: Option<i64>,
    /// Mvc value of the utxo(Irrelavant to token value)
    #[serde(rename = "satoshi", skip_serializing_if = "Option::is_none")]
    pub satoshi: Option<i64>,
    /// Mvc value of the utxo(In string format)
    #[serde(rename = "satoshiString", skip_serializing_if = "Option::is_none")]
    pub satoshi_string: Option<String>,
    /// The hash160 of the script(p2ch address)
    #[serde(rename = "contractAddress", skip_serializing_if = "Option::is_none")]
    pub contract_address: Option<String>,
    /// this the nft send to this contract address
    #[serde(rename = "isReady", skip_serializing_if = "Option::is_none")]
    pub is_ready: Option<bool>,
    /// Flag used for paging
    #[serde(rename = "flag", skip_serializing_if = "Option::is_none")]
    pub flag: Option<String>,
}

impl ContractNftAuctionUtxo {
    /// Contract nft auction Utxo belongs to the specified address
    pub fn new() -> ContractNftAuctionUtxo {
        ContractNftAuctionUtxo {
            address: None,
            txid: None,
            tx_index: None,
            bid_mvc_price: None,
            bid_timestamp: None,
            bidder_address_pkh: None,
            code_hash: None,
            genesis: None,
            end_timestamp: None,
            fee_address_pkh: None,
            fee_amount: None,
            fee_rate: None,
            height: None,
            nft_code_hash: None,
            nft_id: None,
            sender_address_pkh: None,
            sensible_id: None,
            start_mvc_price: None,
            satoshi: None,
            satoshi_string: None,
            contract_address: None,
            is_ready: None,
            flag: None,
        }
    }
}


