/*
 * MicrovisionChain API Document
 *
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.11
 * Contact: heqiming@metasv.com
 * Generated by: https://openapi-generator.tech
 */

/// ContractFtUtxo : Contract fungible token Utxo belongs to the specified address



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContractFtUtxo {
    /// Address string of this utxo
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Codehash of this utxo.
    #[serde(rename = "codeHash", skip_serializing_if = "Option::is_none")]
    pub code_hash: Option<String>,
    /// Genesis of this utxo.
    #[serde(rename = "genesis", skip_serializing_if = "Option::is_none")]
    pub genesis: Option<String>,
    /// Name of the token.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Symbol of the token.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// SensibleId of the token
    #[serde(rename = "sensibleId", skip_serializing_if = "Option::is_none")]
    pub sensible_id: Option<String>,
    /// The decimal position.
    #[serde(rename = "decimal", skip_serializing_if = "Option::is_none")]
    pub decimal: Option<i32>,
    /// Txid for this utxo.
    #[serde(rename = "txid", skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
    /// Output index for the Utxo.
    #[serde(rename = "txIndex", skip_serializing_if = "Option::is_none")]
    pub tx_index: Option<i32>,
    /// Token value of the utxo(Irrelavant to satoshi value).
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<i64>,
    /// Token value of the utxo(In string format)
    #[serde(rename = "valueString", skip_serializing_if = "Option::is_none")]
    pub value_string: Option<String>,
    /// Mvc value of the utxo(Irrelavant to token value)
    #[serde(rename = "satoshi", skip_serializing_if = "Option::is_none")]
    pub satoshi: Option<i64>,
    /// Mvc value of the utxo(In string format)
    #[serde(rename = "satoshiString", skip_serializing_if = "Option::is_none")]
    pub satoshi_string: Option<String>,
    /// The height of this utxo, -1 for unconfirmed utxo.
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i64>,
    /// Flag used for paging
    #[serde(rename = "flag", skip_serializing_if = "Option::is_none")]
    pub flag: Option<String>,
}

impl ContractFtUtxo {
    /// Contract fungible token Utxo belongs to the specified address
    pub fn new() -> ContractFtUtxo {
        ContractFtUtxo {
            address: None,
            code_hash: None,
            genesis: None,
            name: None,
            symbol: None,
            sensible_id: None,
            decimal: None,
            txid: None,
            tx_index: None,
            value: None,
            value_string: None,
            satoshi: None,
            satoshi_string: None,
            height: None,
            flag: None,
        }
    }
}


