/*
 * MicrovisionChain API Document
 *
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.11
 * Contact: heqiming@metasv.com
 * Generated by: https://openapi-generator.tech
 */

/// ContractNftAddressSummary : Get nft summary(count group by genesis) for specific address.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContractNftAddressSummary {
    /// Codehash of this NFT series.
    #[serde(rename = "codeHash", skip_serializing_if = "Option::is_none")]
    pub code_hash: Option<String>,
    /// Genesis of this NFT series..
    #[serde(rename = "genesis", skip_serializing_if = "Option::is_none")]
    pub genesis: Option<String>,
    /// SensibleId of the token
    #[serde(rename = "sensibleId", skip_serializing_if = "Option::is_none")]
    pub sensible_id: Option<String>,
    /// The metanet tx describing the nft.
    #[serde(rename = "metaTxid", skip_serializing_if = "Option::is_none")]
    pub meta_txid: Option<String>,
    /// Symbol of the token.
    #[serde(rename = "metaOutputIndex", skip_serializing_if = "Option::is_none")]
    pub meta_output_index: Option<i32>,
    /// The total supply of this NFT.
    #[serde(rename = "tokenSupply", skip_serializing_if = "Option::is_none")]
    pub token_supply: Option<i64>,
    /// The count of this nft that the address owns.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
}

impl ContractNftAddressSummary {
    /// Get nft summary(count group by genesis) for specific address.
    pub fn new() -> ContractNftAddressSummary {
        ContractNftAddressSummary {
            code_hash: None,
            genesis: None,
            sensible_id: None,
            meta_txid: None,
            meta_output_index: None,
            token_supply: None,
            count: None,
        }
    }
}


