/*
 * MicrovisionChain API Document
 *
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.11
 * Contact: heqiming@metasv.com
 * Generated by: https://openapi-generator.tech
 */

/// ContractFtGenesisCirculation : Get total circulation for specific genesis of ft token.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContractFtGenesisCirculation {
    /// Confirmed circulation of the token(Sum of confirmed amount).
    #[serde(rename = "confirmed", skip_serializing_if = "Option::is_none")]
    pub confirmed: Option<i64>,
    /// Unconfirmed circulation of the token(Unconfirmed new token - Unconfirmed spent).
    #[serde(rename = "unconfirmed", skip_serializing_if = "Option::is_none")]
    pub unconfirmed: Option<i64>,
}

impl ContractFtGenesisCirculation {
    /// Get total circulation for specific genesis of ft token.
    pub fn new() -> ContractFtGenesisCirculation {
        ContractFtGenesisCirculation {
            confirmed: None,
            unconfirmed: None,
        }
    }
}


