/*
 * MicrovisionChain API Document
 *
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.11
 * Contact: heqiming@metasv.com
 * Generated by: https://openapi-generator.tech
 */

/// ContractNftUtxo : Contract non fungible token Utxo belongs to the specified address



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContractNftUtxo {
    /// Address string of this utxo
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Txid for this utxo.
    #[serde(rename = "txid", skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
    /// Output index for the Utxo.
    #[serde(rename = "txIndex", skip_serializing_if = "Option::is_none")]
    pub tx_index: Option<i32>,
    /// Codehash of this utxo.
    #[serde(rename = "codeHash", skip_serializing_if = "Option::is_none")]
    pub code_hash: Option<String>,
    /// Genesis of this utxo.
    #[serde(rename = "genesis", skip_serializing_if = "Option::is_none")]
    pub genesis: Option<String>,
    /// SensibleId of the token
    #[serde(rename = "sensibleId", skip_serializing_if = "Option::is_none")]
    pub sensible_id: Option<String>,
    /// The height of this utxo, -1 for unconfirmed utxo.
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i64>,
    /// The metanet tx describing the nft.
    #[serde(rename = "metaTxid", skip_serializing_if = "Option::is_none")]
    pub meta_txid: Option<String>,
    /// Symbol of the token.
    #[serde(rename = "metaOutputIndex", skip_serializing_if = "Option::is_none")]
    pub meta_output_index: Option<i32>,
    /// The total supply of this NFT.
    #[serde(rename = "tokenSupply", skip_serializing_if = "Option::is_none")]
    pub token_supply: Option<i64>,
    /// The index of this NFT.
    #[serde(rename = "tokenIndex", skip_serializing_if = "Option::is_none")]
    pub token_index: Option<i64>,
    /// Mvc value of the utxo(Irrelavant to token value)
    #[serde(rename = "satoshi", skip_serializing_if = "Option::is_none")]
    pub satoshi: Option<i64>,
    /// Mvc value of the utxo(In string format)
    #[serde(rename = "satoshiString", skip_serializing_if = "Option::is_none")]
    pub satoshi_string: Option<String>,
    /// Flag used for paging
    #[serde(rename = "flag", skip_serializing_if = "Option::is_none")]
    pub flag: Option<String>,
}

impl ContractNftUtxo {
    /// Contract non fungible token Utxo belongs to the specified address
    pub fn new() -> ContractNftUtxo {
        ContractNftUtxo {
            address: None,
            txid: None,
            tx_index: None,
            code_hash: None,
            genesis: None,
            sensible_id: None,
            height: None,
            meta_txid: None,
            meta_output_index: None,
            token_supply: None,
            token_index: None,
            satoshi: None,
            satoshi_string: None,
            flag: None,
        }
    }
}


