/*
 * MicrovisionChain API Document
 *
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.11
 * Contact: heqiming@metasv.com
 * Generated by: https://openapi-generator.tech
 */

/// ContractUniqueUtxo : Contract unique Utxo indexed by codeHash and genesis.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContractUniqueUtxo {
    /// Txid for this utxo.
    #[serde(rename = "txid", skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
    /// Output index for the Utxo.
    #[serde(rename = "txIndex", skip_serializing_if = "Option::is_none")]
    pub tx_index: Option<i32>,
    /// Codehash of this utxo.
    #[serde(rename = "codeHash", skip_serializing_if = "Option::is_none")]
    pub code_hash: Option<String>,
    /// Genesis of this utxo.
    #[serde(rename = "genesis", skip_serializing_if = "Option::is_none")]
    pub genesis: Option<String>,
    /// SensibleId of the token
    #[serde(rename = "sensibleId", skip_serializing_if = "Option::is_none")]
    pub sensible_id: Option<String>,
    /// The height of this utxo, -1 for unconfirmed utxo.
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i64>,
    /// The hex encoded customData
    #[serde(rename = "customData", skip_serializing_if = "Option::is_none")]
    pub custom_data: Option<String>,
    /// Mvc value of the utxo(Irrelavant to token value)
    #[serde(rename = "satoshi", skip_serializing_if = "Option::is_none")]
    pub satoshi: Option<i64>,
    /// Mvc value of the utxo(In string format)
    #[serde(rename = "satoshiString", skip_serializing_if = "Option::is_none")]
    pub satoshi_string: Option<String>,
}

impl ContractUniqueUtxo {
    /// Contract unique Utxo indexed by codeHash and genesis.
    pub fn new() -> ContractUniqueUtxo {
        ContractUniqueUtxo {
            txid: None,
            tx_index: None,
            code_hash: None,
            genesis: None,
            sensible_id: None,
            height: None,
            custom_data: None,
            satoshi: None,
            satoshi_string: None,
        }
    }
}


