/*
 * MicrovisionChain API Document
 *
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.11
 * Contact: heqiming@metasv.com
 * Generated by: https://openapi-generator.tech
 */

/// TxDetail : Parsed tx info



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TxDetail {
    #[serde(rename = "txDetail", skip_serializing_if = "Option::is_none")]
    pub tx_detail: Option<Box<crate::models::BlockTx>>,
    #[serde(rename = "inputs", skip_serializing_if = "Option::is_none")]
    pub inputs: Option<Vec<crate::models::TxInput>>,
    #[serde(rename = "outputs", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Vec<crate::models::TxOutput>>,
}

impl TxDetail {
    /// Parsed tx info
    pub fn new() -> TxDetail {
        TxDetail {
            tx_detail: None,
            inputs: None,
            outputs: None,
        }
    }
}


