/*
 * MicrovisionChain API Document
 *
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.11
 * Contact: heqiming@metasv.com
 * Generated by: https://openapi-generator.tech
 */

/// TxOutput : Parsed outputs from raw tx.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TxOutput {
    /// Output index of the tx.
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<i32>,
    /// Bitcoin Value in this output.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<i64>,
    /// Parsed address from output
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Hex formatted lockScript
    #[serde(rename = "lockScript", skip_serializing_if = "Option::is_none")]
    pub lock_script: Option<String>,
}

impl TxOutput {
    /// Parsed outputs from raw tx.
    pub fn new() -> TxOutput {
        TxOutput {
            index: None,
            value: None,
            address: None,
            lock_script: None,
        }
    }
}


