/*
 * MicrovisionChain API Document
 *
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.11
 * Contact: heqiming@metasv.com
 * Generated by: https://openapi-generator.tech
 */

/// TxRaw : Raw hex formatted Tx returned.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TxRaw {
    /// hex formatted raw tx.
    #[serde(rename = "hex", skip_serializing_if = "Option::is_none")]
    pub hex: Option<String>,
}

impl TxRaw {
    /// Raw hex formatted Tx returned.
    pub fn new() -> TxRaw {
        TxRaw {
            hex: None,
        }
    }
}


