/*
 * MicrovisionChain API Document
 *
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.11
 * Contact: heqiming@metasv.com
 * Generated by: https://openapi-generator.tech
 */

/// XpubDetail : Registered Xpub detail



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct XpubDetail {
    /// String encoded extended pubkey (xpub)
    #[serde(rename = "xpub", skip_serializing_if = "Option::is_none")]
    pub xpub: Option<String>,
    /// Next unused receive index, path /0/index
    #[serde(rename = "receiveIndex", skip_serializing_if = "Option::is_none")]
    pub receive_index: Option<i32>,
    /// Max lookahead receive index.
    #[serde(rename = "maxReceiveIndex", skip_serializing_if = "Option::is_none")]
    pub max_receive_index: Option<i32>,
    /// Next unused change index, path /1/index
    #[serde(rename = "changeIndex", skip_serializing_if = "Option::is_none")]
    pub change_index: Option<i32>,
    /// Max lookahead change index.
    #[serde(rename = "maxChangeIndex", skip_serializing_if = "Option::is_none")]
    pub max_change_index: Option<i32>,
    /// Current xpub process mode, 0 means preparing(not ready), 1 means synchronizing(ready)
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<i32>,
    /// Skip blocks before skipHeight while searching transactions. This will speed up sync time.
    #[serde(rename = "skipHeight", skip_serializing_if = "Option::is_none")]
    pub skip_height: Option<i64>,
    /// Xpub current processed height.
    #[serde(rename = "processHeight", skip_serializing_if = "Option::is_none")]
    pub process_height: Option<i64>,
}

impl XpubDetail {
    /// Registered Xpub detail
    pub fn new() -> XpubDetail {
        XpubDetail {
            xpub: None,
            receive_index: None,
            max_receive_index: None,
            change_index: None,
            max_change_index: None,
            mode: None,
            skip_height: None,
            process_height: None,
        }
    }
}


