/*
 * MicrovisionChain API Document
 *
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.11
 * Contact: heqiming@metasv.com
 * Generated by: https://openapi-generator.tech
 */

/// XpubLiteBalance : Balance for xpub lite wallet



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct XpubLiteBalance {
    /// confirmed balance plus unconfirmed balance
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<i64>,
}

impl XpubLiteBalance {
    /// Balance for xpub lite wallet
    pub fn new() -> XpubLiteBalance {
        XpubLiteBalance {
            balance: None,
        }
    }
}


